image:
  name: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
stages:
  - build

build_stage:
  stage: build
  before_script:
  - export CURRENT_COMMIT=${CI_COMMIT_SHA::8}
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg build_env=prod -f docker/Dockerfile --cache-from $CI_REGISTRY_IMAGE:$BRANCH_NAME --tag $CI_REGISTRY_IMAGE:$CURRENT_COMMIT --tag $CI_REGISTRY_IMAGE:master --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CURRENT_COMMIT
    - docker push $CI_REGISTRY_IMAGE:master
    - docker push $CI_REGISTRY_IMAGE:latest\
  only:
    - master
  tags:
    - staging
