image:
  name: docker:19.03.1

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  
stages:
  - build
  - deploy-stage
  - prep-prod
  - deploy-prod

build_stage:
  stage: build
  before_script:
  - export CURRENT_COMMIT=${CI_COMMIT_SHA::8}
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg build_env=prod -f docker/Dockerfile --cache-from $CI_REGISTRY_IMAGE:$BRANCH_NAME --tag $CI_REGISTRY_IMAGE:$CURRENT_COMMIT --tag $CI_REGISTRY_IMAGE:master --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CURRENT_COMMIT
    - docker push $CI_REGISTRY_IMAGE:master
    - docker push $CI_REGISTRY_IMAGE:latest\
  only:
    - master
  tags:
    - staging
    
deploy_stage:
  stage: deploy-stage
  variables:
    GIT_STRATEGY: none
    KUBE_API_CA: $STAGE_KUBE_API_CA
    KUBE_API_SERVER: $STAGE_KUBE_API_SERVER
    KUBE_API_USERNAME: $STAGE_KUBE_API_USERNAME
    KUBE_API_PASSWORD: $STAGE_KUBE_API_PASSWORD
    KUBE_DEPLOYMENT_NAME: $STAGE_KUBE_DEPLOYMENT_NAME
  image: registry.gitlab.qsoft.ru/system-software/k8s-tool:latest
  script:
    - kubectl -n benfin rollout restart deployment $KUBE_DEPLOYMENT_NAME
  only:
    - master
  tags:
    - stage
    
tag_prod:
  stage: prep-prod
  variables:
    GIT_STRATEGY: none
  before_script:
  - export CURRENT_COMMIT=${CI_COMMIT_SHA::8}
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CURRENT_COMMIT || true
    - docker tag  $CI_REGISTRY_IMAGE:$CURRENT_COMMIT $CI_REGISTRY_IMAGE:prod
    - docker push $CI_REGISTRY_IMAGE:prod
  only:
    - master
  when: manual
  tags:
    - prod

deploy_prod-app:
  stage: deploy-prod
  variables:
    GIT_STRATEGY: none
    KUBE_API_CA: $PROD_KUBE_API_CA
    KUBE_API_SERVER: $PROD_KUBE_API_SERVER
    KUBE_API_TOKEN: $PROD_KUBE_API_TOKEN
    KUBE_DEPLOYMENT_NAME: $PROD_KUBE_DEPLOYMENT_NAME
  image: registry.gitlab.qsoft.ru/system-software/k8s-tool:latest
  script:
    - kubectl -n benfin rollout restart deployment $KUBE_DEPLOYMENT_NAME
  only:
    - master
  when: manual
  tags:
    - prod

deploy_prod-bg:
  stage: deploy-prod
  variables:
    GIT_STRATEGY: none
    KUBE_API_CA: $PROD_KUBE_API_CA
    KUBE_API_SERVER: $PROD_KUBE_API_SERVER
    KUBE_API_TOKEN: $PROD_KUBE_API_TOKEN
    KUBE_DEPLOYMENT_NAME: $PROD_KUBE_DEPLOYMENT_NAME
  image: registry.gitlab.qsoft.ru/system-software/k8s-tool:latest
  script:
    - kubectl -n benfin rollout restart deployment $KUBE_DEPLOYMENT_NAME-bg
  only:
    - master
  when: manual
  tags:
    - prod
